# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRTapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspot',
            old_name='createdTime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='hotspot',
            old_name='modifiedTime',
            new_name='modified_time',
        ),
        migrations.RenameField(
            model_name='hotspot',
            old_name='spotCommit',
            new_name='spot_commit',
        ),
        migrations.RenameField(
            model_name='hotspot',
            old_name='spotImgSource',
            new_name='spot_img_source',
        ),
        migrations.RenameField(
            model_name='hotspot',
            old_name='spotName',
            new_name='spot_name',
        ),
        migrations.RenameField(
            model_name='hotspot',
            old_name='spotStop',
            new_name='spot_stop',
        ),
        migrations.RenameField(
            model_name='hotspot',
            old_name='spotType',
            new_name='spot_type',
        ),
        migrations.RenameField(
            model_name='mrtstops',
            old_name='stopName',
            new_name='stop_name',
        ),
    ]
