# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRTapps', '0002_auto_20160602_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrtstops',
            name='stop_color',
            field=models.CharField(choices=[('文湖線', 'brown'), ('淡水信義線', 'red'), ('松山新店線', 'green'), ('中和新蘆線', 'yellow'), ('板南線', 'blue')], default='文湖線', max_length=10),
        ),
    ]
