# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotType', models.CharField(choices=[('美食', '美食'), ('景點', '景點')], default='美食', max_length=10)),
                ('spotName', models.CharField(max_length=20)),
                ('spotCommit', models.TextField(max_length=500)),
                ('spotImgSource', models.CharField(max_length=50)),
                ('createdTime', models.DateTimeField(editable=False)),
                ('modifiedTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MRTStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopName', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='hotspot',
            name='spotStop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRTapps.MRTStops'),
        ),
    ]
